const weldPropsMenuBox = overlayGroup
    .append("rect")
    .attr("x", -5)
    .attr("y", settingsButtonProps.y - buttonPitch*4-2.5)
    .attr("width", 160)
    .attr("height", buttonHeight+buttonPitch*3+5)
    .attr("rx", 5)
    .attr("ry", 5)
    .attr("fill", "lightgray")
    .attr("fill-opacity", 0.75)
    .attr("stroke", "black")
    .attr("stroke-width", 0.5)
    .attr("stroke-opacity", 1)
    // .style("pointer-events", "none")
    .style("display", "none")
    .on("mousedown", function(event) {
        event.stopPropagation();
    })

const weldPropsButton = overlayGroup
    .append("rect")
    .attr("x", 5)
    .attr("y", firstButtonY-buttonPitch*2)
    .attr("width", buttonWidth)
    .attr("height", buttonHeight)
    .attr("rx", buttonCorner)
    .attr("ry", buttonCorner)
    .attr("fill", "black")
    .attr("fill-opacity", 0)
    .attr("stroke", "black")
    .attr("stroke-width", 0.5)
    .attr("stroke-opacity", 0.25)
    // .on("click", function() {showHideProps()})
    .style("display", "none")
const weldPropsIcon = overlayGroup
    .append("text")
    .attr("font-size", "16pt")
    .attr("text-anchor", "middle")
    // .attr("alignment-baseline", "text-before-edge")
    .style("pointer-events", "none")
    .attr("x", 5+(buttonWidth-2)/2)
    .attr("y", settingsButtonProps.y+settingsButtonProps.height/2-1.5)
    .attr("dy", "0.35em")
    .attr("opacity", 0.75)
    .text("🛠")
    .style("display", "none")